apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-09-21T01:15:19Z"
  generation: 2
  labels:
    app: file-uploader-app
  name: file-uploader-app
  namespace: default
  resourceVersion: "4383"
  uid: f46bb2bb-00e2-4dee-911a-0f99985cfe04
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: file-uploader-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: file-uploader-app
    spec:
      containers:
      - image: gcr.io/myfirstapp-72240/file-uploader:latest
        imagePullPolicy: Always
        name: file-uploader
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: access_key.json
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-21T01:15:27Z"
    lastUpdateTime: "2024-09-21T01:15:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-09-21T01:15:19Z"
    lastUpdateTime: "2024-09-21T01:17:27Z"
    message: ReplicaSet "file-uploader-app-6f994f67d4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
